# Generated by Django 5.2.6 on 2025-09-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_DB',
            fields=[
                ('car_Name', models.CharField(max_length=10)),
                ('reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('carowner_email', models.EmailField(max_length=254)),
                ('carmanufature_date', models.DateField()),
                ('car_mileage', models.FloatField()),
            ],
        ),
    ]
